apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: infoline
  labels:
    app: infoline-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: infoline-frontend
