apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: infoline
  labels:
    app: infoline-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: infoline-api
